safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/odom"
    safety_topic: "/vesc/low_level/input/safety"
    goal_distance: 7.
    bound_angle: 7.5
    left_right_angle: 45.0
    front_steer_thres: 